### ISSUE TITLE
16.04 -  4.8.0-51-generic -- BUILD FAIL

### ISSUE THREAD

**Issue by alphaaurigae** [luisgg/ophcrack#1]
```
```
12:55 $ cd /opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/
✔ /opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack [master|✚ 2…11] 
12:55 $ make clean
rm -f *~
make[1]: Entering directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src/samdump2'
rm -f *.o *~
rm -f libsamdump2.a
make[1]: Leaving directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src/samdump2'
make[1]: Entering directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src/ntproba'
rm -f *.o *~
make[1]: Leaving directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src/ntproba'
make[1]: Entering directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src'
rm -f *.o *~
rm -f ophcrack
rm -f libophcrack.a
make[1]: Leaving directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src'
make[1]: Entering directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src/gui'
rm -f moc_ophcrackgui.cpp moc_hashmodel.cpp moc_tablemodel.cpp moc_progdelegate.cpp moc_tabledialog.cpp moc_singlehashdialog.cpp moc_hashview.cpp moc_samdialog.cpp moc_aboutdialog.cpp moc_helpdialog.cpp moc_graphdialog.cpp moc_exportdialog.cpp
rm -f qrc_gui.cpp
rm -f ui_ophcrackgui.h ui_tabledialog.h ui_singlehashdialog.h ui_samdialog.h ui_aboutdialog.h ui_helpdialog.h ui_graphdialog.h ui_exportdialog.h
rm -f main.o ophcrackgui.o hashmodel.o tablemodel.o progdelegate.o tabledialog.o singlehashdialog.o hashview.o samdialog.o aboutdialog.o helpdialog.o graphdialog.o histogram_item.o exportdialog.o moc_ophcrackgui.o moc_hashmodel.o moc_tablemodel.o moc_progdelegate.o moc_tabledialog.o moc_singlehashdialog.o moc_hashview.o moc_samdialog.o moc_aboutdialog.o moc_helpdialog.o moc_graphdialog.o moc_exportdialog.o qrc_gui.o
rm -f *~ core *.core
make[1]: Leaving directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src/gui'
✔ /opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack [master|✚ 2…9] 
12:55 $ git clean -f
Removing Makefile
Removing config.h
Removing config.log
Removing config.status
Removing src/Makefile
Removing src/gui/Makefile
Removing src/gui/ophcrack_win32.rc
Removing src/ntproba/Makefile
Removing src/samdump2/Makefile
✔ /opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack [master|✚ 2] 
12:55 $ git pull
Already up-to-date.
✔ /opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack [master|✚ 2] 
12:55 $ 
✔ /opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack [master|✚ 2] 
12:55 $ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking if debugging is enabled... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking for Mac OS X or WIN32 or Solaris... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for pthread_mutex_init in -lpthread... yes
checking for libssl... OpenSSL found in /usr
checking for XML_ParserCreate in -lexpat... yes
checking for sqrt in -lm... yes
checking for ANSI C header files... (cached) yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking sys/sysinfo.h usability... yes
checking sys/sysinfo.h presence... yes
checking for sys/sysinfo.h... yes
checking sys/sysctl.h usability... yes
checking sys/sysctl.h presence... yes
checking for sys/sysctl.h... yes
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking libkern/OSByteOrder.h usability... no
checking libkern/OSByteOrder.h presence... no
checking for libkern/OSByteOrder.h... no
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uchar_t... no
checking for ulong_t... no
checking for struct sysinfo... yes
checking if graph drawing is enabled... yes
checking for libqwt... Qwt found in /usr
checking whether we want to build ophcrack gui... yes
checking for egrep... (cached) /bin/grep -E
checking for qmake-qt4... /usr/bin/qmake-qt4
checking for qmake... /usr/bin/qmake
checking for Qt4 version of qmake... /usr/bin/qmake-qt4
checking for egrep... (cached) /bin/grep -E
checking for moc-qt4... /usr/bin/moc-qt4
checking for moc... /usr/bin/moc
checking for Qt4 version of moc... /usr/bin/moc-qt4
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working memcmp... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... yes
checking for working mmap... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking types of arguments for select... int,fd_set *,struct timeval *
checking for floor... yes
checking for gettimeofday... yes
checking for memchr... yes
checking for memset... yes
checking for munmap... yes
checking for regcomp... yes
checking for select... yes
checking for sqrt... yes
checking for strchr... yes
checking for strdup... yes
checking for strndup... yes
checking for strtoul... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/test/Makefile
config.status: creating src/gui/qmake.sh
config.status: creating src/gui/gui.pro
config.status: creating src/gui/ophcrack_win32.rc
config.status: creating src/gui/Info.plist
config.status: creating src/ntproba/Makefile
config.status: creating src/samdump2/Makefile
config.status: creating config.h
configure: Generating GUI Makefile with qmake
WARNING: Failure to find: ui_ophcrackgui.h
WARNING: Failure to find: ui_tabledialog.h

====================================================
ophcrack has been successfully configured as follow
====================================================

 Install directory: /usr/local

 GUI: yes
 Graph display: yes
 Debugging: no

====================================================

Now enter 'make' to compile
followed by 'make install' to install

✔ /opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack [master|✚ 2…9] 
12:56 $ make -j 2
make[1]: Entering directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src/samdump2'
gcc -g -O2 -O2 -DNDEBUG -Wall -std=gnu9x -pedantic -I.. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I.. -I/usr/include -I./.. -I./../..   -c -o hive.o hive.c
gcc -g -O2 -O2 -DNDEBUG -Wall -std=gnu9x -pedantic -I.. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I.. -I/usr/include -I./.. -I./../..   -c -o bkhive.o bkhive.c
gcc -g -O2 -O2 -DNDEBUG -Wall -std=gnu9x -pedantic -I.. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I.. -I/usr/include -I./.. -I./../..   -c -o samdump2.o samdump2.c
samdump2.c: In function ‘str_to_key’:
samdump2.c:75:2: warning: implicit declaration of function ‘des_set_odd_parity’ [-Wimplicit-function-declaration]
  des_set_odd_parity((des_cblock *)key);
  ^~~~~~~~~~~~~~~~~~
samdump2.c:75:22: error: ‘des_cblock’ undeclared (first use in this function)
  des_set_odd_parity((des_cblock *)key);
                      ^~~~~~~~~~
samdump2.c:75:22: note: each undeclared identifier is reported only once for each function it appears in
samdump2.c:75:34: error: expected expression before ‘)’ token
  des_set_odd_parity((des_cblock *)key);
                                  ^
samdump2.c: In function ‘samdump2’:
samdump2.c:213:3: error: unknown type name ‘des_key_schedule’
   des_key_schedule ks1, ks2;
   ^~~~~~~~~~~~~~~~
samdump2.c:214:3: error: unknown type name ‘des_cblock’
   des_cblock deskey1, deskey2;
   ^~~~~~~~~~
samdump2.c:421:23: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       sid_to_key1(rid,(unsigned char *)deskey1);
                       ^
samdump2.c:422:7: warning: implicit declaration of function ‘des_set_key_checked’ [-Wimplicit-function-declaration]
       des_set_key_checked((des_cblock *)deskey1,ks1);
       ^~~~~~~~~~~~~~~~~~~
samdump2.c:422:28: error: ‘des_cblock’ undeclared (first use in this function)
       des_set_key_checked((des_cblock *)deskey1,ks1);
                            ^~~~~~~~~~
samdump2.c:422:40: error: expected expression before ‘)’ token
       des_set_key_checked((des_cblock *)deskey1,ks1);
                                        ^
samdump2.c:423:23: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       sid_to_key2(rid,(unsigned char *)deskey2);
                       ^
samdump2.c:424:7: warning: implicit declaration of function ‘des_set_key_unchecked’ [-Wimplicit-function-declaration]
       des_set_key_unchecked((des_cblock *)deskey2,ks2);
       ^~~~~~~~~~~~~~~~~~~~~
samdump2.c:424:42: error: expected expression before ‘)’ token
       des_set_key_unchecked((des_cblock *)deskey2,ks2);
                                          ^
samdump2.c:427:7: warning: implicit declaration of function ‘des_ecb_encrypt’ [-Wimplicit-function-declaration]
       des_ecb_encrypt((des_cblock *)obfkey,
       ^~~~~~~~~~~~~~~
samdump2.c:427:36: error: expected expression before ‘)’ token
       des_ecb_encrypt((des_cblock *)obfkey,
                                    ^
samdump2.c:429:36: error: expected expression before ‘)’ token
       des_ecb_encrypt((des_cblock *)(obfkey + 8),
                                    ^
samdump2.c:430:22: error: expected expression before ‘)’ token
         (des_cblock *)&fb[8], ks2, DES_DECRYPT);
                      ^
samdump2.c:474:18: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  sid_to_key1(rid,(unsigned char *)deskey1);
                  ^
samdump2.c:475:2: warning: implicit declaration of function ‘des_set_key’ [-Wimplicit-function-declaration]
  des_set_key((des_cblock *)deskey1,ks1);
  ^~~~~~~~~~~
samdump2.c:475:27: error: expected expression before ‘)’ token
  des_set_key((des_cblock *)deskey1,ks1);
                           ^
samdump2.c:476:18: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  sid_to_key2(rid,(unsigned char *)deskey2);
                  ^
samdump2.c:477:27: error: expected expression before ‘)’ token
  des_set_key((des_cblock *)deskey2,ks2);
                           ^
samdump2.c:481:36: error: expected expression before ‘)’ token
       des_ecb_encrypt((des_cblock *)obfkey,
                                    ^
samdump2.c:483:36: error: expected expression before ‘)’ token
       des_ecb_encrypt((des_cblock *)(obfkey + 8),
                                    ^
samdump2.c:484:22: error: expected expression before ‘)’ token
         (des_cblock *)&fb[8], ks2, DES_DECRYPT);
                      ^
samdump2.c:213:25: warning: unused variable ‘ks2’ [-Wunused-variable]
   des_key_schedule ks1, ks2;
                         ^~~
samdump2.c:213:20: warning: unused variable ‘ks1’ [-Wunused-variable]
   des_key_schedule ks1, ks2;
                    ^~~
<builtin>: recipe for target 'samdump2.o' failed
make[1]: *** [samdump2.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack/src/samdump2'
Makefile:49: recipe for target 'all' failed
make: *** [all] Error 1
✘-2 /opt/ITSEC/4.Password/2.Local/1.Brute/ophcrack/luisgg/ophcrack [master|✚ 2…11] 

```
```

**Comment by alphaaurigae** [comment]
closing the issue, cant reproduce. It works with java 1.8.0_152-ea on 16.04.
